# Generated by Django 5.2.3 on 2025-11-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del juego')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('categoria', models.CharField(help_text='Ej: Estrategia, Cartas, Miniaturas, etc.', max_length=50, verbose_name='Categoría')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='juegos/', verbose_name='Imagen del juego')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'ordering': ['-created'],
            },
        ),
    ]
