# Generated by Django 5.2.3 on 2025-11-10 19:28

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def migrate_noticia_categorias(apps, schema_editor):
    Categoria = apps.get_model('posteo', 'Categoria')
    Noticia = apps.get_model('posteo', 'Noticia')

    for noticia in Noticia.objects.all():
        nombre_categoria = noticia.categoria_text or 'General'
        slug = slugify(nombre_categoria)
        categoria, created = Categoria.objects.get_or_create(
            nombre=nombre_categoria,
            defaults={
                'slug': slug,
            },
        )

        # Si la categoría ya existía pero no posee slug, la actualizamos
        if not categoria.slug:
            categoria.slug = slug
            categoria.save(update_fields=['slug'])

        noticia.categoria = categoria
        noticia.save(update_fields=['categoria'])


class Migration(migrations.Migration):

    dependencies = [
        ('posteo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='categoria',
            new_name='categoria_text',
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='noticias', to='posteo.categoria', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('aprobado', models.BooleanField(default=True, verbose_name='Aprobado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='posteo.noticia', verbose_name='Noticia')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['created'],
            },
        ),
        migrations.RunPython(migrate_noticia_categorias, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='noticia',
            name='categoria_text',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias', to='posteo.categoria', verbose_name='Categoría'),
        ),
    ]
