# Generated by Django 5.2.3 on 2025-11-10 19:36

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def create_default_author(apps, schema_editor):
    Autor = apps.get_model('posteo', 'Autor')
    Noticia = apps.get_model('posteo', 'Noticia')

    autor, _ = Autor.objects.get_or_create(
        nombre='Equipo Blogfiction',
        defaults={
            'slug': slugify('Equipo Blogfiction'),
            'bio': 'Equipo editorial de Blogfiction.cl',
        }
    )

    Noticia.objects.filter(autor__isnull=True).update(autor=autor)


class Migration(migrations.Migration):

    dependencies = [
        ('posteo', '0002_categoria_alter_noticia_categoria_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='autores/', verbose_name='Foto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='posteo.autor', verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='noticias', to='posteo.etiqueta', verbose_name='Etiquetas'),
        ),
        migrations.RunPython(create_default_author, migrations.RunPython.noop),
    ]
