# Generated by Django 5.2.3 on 2025-11-29 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posteo', '0003_autor_etiqueta_noticia_autor_noticia_etiquetas'),
        ('posteo', '0004_crear_grupos_permisos'),
    ]

    operations = [
    ]
